# -*- coding: utf-8 -*-
"""-Lectura-de-Datos-GPS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4cfEfZwzGU4h7JG35UkCKQ_I6WYFKtJ
"""

# Commented out IPython magic to ensure Python compatibility.
#Programa que muestra y grafica las cordenadas importadas desde un archivo .csv
#O2 Proyecto - Manuel Guadalupe Cisneros Castillo 
import plotly.express as px
import pandas as pd
from google.colab import files
from google.colab import drive
import os
from geopy.geocoders import Nominatim

drive.mount('/content/drive') #Debemos confirmar acceso a nuestra cuenta para el COLAB
# %cd "/content/drive/My Drive/Colab Notebooks/"
# %pwd
fuente = '.'
arch = "datosGPS.csv"
df = pd.read_csv("datosGPS.csv")
print(df)

fig = px.scatter_geo(df,lat='easting',lon='northing', hover_name="ID")
fig.update_layout(title = 'Mis Datos', title_x=0.5)
fig.show()

geolocalizador = Nominatim()
ubicacion = geolocalizador.reverse("19.33399138806788, -103.649772224436")
print(ubicacion.address)
print(ubicacion.latitude, ubicacion.longitude)
print(ubicacion.raw)